In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import math

In [2]:
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"

# Assign colum names to the dataset
names = ['sepal-length', 'sepal-width', 'petal-length', 'petal-width', 'Class']

# Read dataset to pandas dataframe
dataset = pd.read_csv(url, names=names)

In [3]:
dataset.head()

sepal-length  sepal-width  petal-length  petal-width        Class
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [4]:
dataset

sepal-length  sepal-width  petal-length  petal-width           Class
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [5]:
num_neighbors = 5

In [6]:
training=dataset.values[0:148,0:4]
training

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3.0, 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5.0, 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5.0, 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3.0, 1.4, 0.1],
       [4.3, 3.0, 1.1, 0.1],
       [5.8, 4.0, 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1.0, 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5.0, 3.0, 1.6, 0.2],
       [5.0, 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [7]:
def str_column_to_float(dataset, column):
	for row in dataset:
		row[column] = float(row[column])

for i in range(len(training[0])):
  str_column_to_float(training,i)

training

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3.0, 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5.0, 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5.0, 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3.0, 1.4, 0.1],
       [4.3, 3.0, 1.1, 0.1],
       [5.8, 4.0, 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1.0, 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5.0, 3.0, 1.6, 0.2],
       [5.0, 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [8]:
trainingclass=dataset.values[0:148,-1]
trainingclass

array(['Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versic

In [9]:
def euclidean_distance(row1, row2):
	distance = 0.0
	for i in range(len(row1)-1):
		distance += (row1[i] - row2[i])**2
	return (math.sqrt(distance))

In [10]:
testing=dataset.values[148,0:4]
testing

array([6.2, 3.4, 5.4, 2.3], dtype=object)

In [11]:
unique_list=[]
for x in trainingclass:
  if x not in unique_list:
    unique_list.append(x)

print(unique_list)
for i in range(len(trainingclass)):
  for k in range(len(unique_list)):
    if(trainingclass[i]==unique_list[k]):
      trainingclass[i]=k
print(trainingclass)

['Iris-setosa', 'Iris-versicolor', 'Iris-virginica']
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2]


In [12]:
distance=[]
for i in range(len(training)):
  distance.append([euclidean_distance((training[i]),(testing)),trainingclass[i]])

distance

[[4.149698784249286, 0],
 [4.224926034855521, 0],
 [4.370354676682432, 0],
 [4.226109321823088, 0],
 [4.180908992073374, 0],
 [3.818376618407357, 0],
 [4.308131845707604, 0],
 [4.080441152620633, 0],
 [4.414748010928823, 0],
 [4.12189276910499, 0],
 [3.9924929555354263, 0],
 [4.049691346263318, 0],
 [4.256759330758553, 0],
 [4.71805044483418, 0],
 [4.261455150532504, 0],
 [4.0570925550201595, 0],
 [4.207136793592527, 0],
 [4.149698784249286, 0],
 [3.7549966711037177, 0],
 [4.0718546143004675, 0],
 [3.78549864614954, 0],
 [4.06324993078201, 0],
 [4.686149805543993, 0],
 [3.861346915261565, 0],
 [3.7696153649941535, 0],
 [4.004996878900157, 0],
 [3.984971769034255, 0],
 [4.0274061131204535, 0],
 [4.123105625617661, 0],
 [4.090232267243512, 0],
 [4.060788100849391, 0],
 [3.981205847478877, 0],
 [4.08656334834051, 0],
 [4.1388404173149755, 0],
 [4.12189276910499, 0],
 [4.37264222181509, 0],
 [4.160528812542945, 0],
 [4.12189276910499, 0],
 [4.495553358597805, 0],
 [4.052159917870963, 0],
 

In [13]:
distance.sort()
distance

[[0.22360679774997816, 2],
 [0.3000000000000001, 2],
 [0.374165738677394, 2],
 [0.46904157598234314, 2],
 [0.5099019513592783, 2],
 [0.5385164807134504, 2],
 [0.5477225575051659, 2],
 [0.5916079783099616, 2],
 [0.5916079783099616, 2],
 [0.6164414002968973, 2],
 [0.6164414002968973, 2],
 [0.6403124237432845, 2],
 [0.6480740698407861, 2],
 [0.6633249580710799, 2],
 [0.6633249580710799, 2],
 [0.6708203932499369, 2],
 [0.6782329983125271, 2],
 [0.7000000000000003, 1],
 [0.7141428428542852, 1],
 [0.7280109889280515, 2],
 [0.7348469228349533, 2],
 [0.7483314773547887, 2],
 [0.7549834435270751, 1],
 [0.761577310586391, 2],
 [0.781024967590666, 2],
 [0.7874007874011811, 1],
 [0.7874007874011811, 2],
 [0.8062257748298546, 2],
 [0.8185352771872454, 2],
 [0.8306623862918072, 2],
 [0.8485281374238575, 2],
 [0.8602325267042629, 2],
 [0.8602325267042629, 2],
 [0.8660254037844384, 2],
 [0.8660254037844389, 1],
 [0.9000000000000007, 1],
 [0.91104335791443, 1],
 [0.91104335791443, 1],
 [0.9219544457292

In [14]:
identify=[0 for i in range(len(unique_list))]
for i in range(num_neighbors):
  identify[distance[i][1]]=identify[distance[i][1]]+1

identify

print("The predicted class is: ",unique_list[identify.index(max(identify))])

The predicted class is:  Iris-virginica
